
<div class="panel panel-default panel-primary">
	<!-- Default panel contents -->
	<div class="panel-heading">
	   <h4 class="panel-title">用户信息</h4>
	</div>
	<!-- List group -->
	<ul class="list-group">
          <li class="list-group-item">
              <form class="form-inline" role="form">
                  <div class="form-group">
                      <label class="sr-only" for="oldPassword">oldpassword</label>
                      <input type="password" class="form-control" id="oldPassword" placeholder="旧密码">
                  </div>
                  <div class="form-group">
                      <label class="sr-only" for="password1">password1</label>
                      <input type="password" class="form-control" id="password1" placeholder="新密码">
                  </div>
                  <div class="form-group">
                      <label class="sr-only" for="password2">password2</label>
                      <input type="password" class="form-control" id="password2" placeholder="确认新密码">
                  </div>
                  <button type="button" class="btn btn-primary update_password">修改密码</button>
            </form>
          </li>
          <li class="list-group-item">
            <form class="form-horizontal" role="form">
              <div class="form-group">
                <div class="col-md-4">
                  <input type="text" class="form-control" id="money" placeholder="金额">
                </div>
              </div>
              <div class="form-group">
                <div class="col-md-10">
                 <textarea class="form-control" rows="3" placeholder="描述信息......"></textarea>
                </div>
              </div>
              <div class="form-group">
                <div class="col-md-10">
                  <button type="button" class="btn btn-primary btn-block">添加记录</button>
                </div>
              </div>
            </form>
          </li>
          <li class="list-group-item">
            <div class="row">
                <div class="col-md-1">
                  <button class="btn btn-primary">加一顿</button>
                </div>
                <div class="col-md-1">
                  <button class="btn btn-primary">减一顿</button>
                </div>
            </div>
          </li>
    </ul>
</div>