
<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">
	   <h4>用户信息</h4>
	</div>
	<!-- List group -->
	<ul class="list-group">
          <li class="list-group-item">
              <form class="form-inline" role="form">
              <div class="form-group">
                <input type="password" class="form-control" id="oldPassword" placeholder="旧密码">
              </div>
              <div class="form-group">
                <input type="password" class="form-control" id="password1" placeholder="新密码">
              </div>
              <div class="form-group">
                <input type="password" class="form-control" id="password2" placeholder="确认新密码">
              </div>
              <button type="submit" class="btn btn-primary update_password">修改密码</button>
              <span></span>
            </form>
          </li>
          <li class="list-group-item">
            <form class="form-horizontal" role="form">
              <div class="form-group">
                <div class="col-sm-4">
                  <input type="text" class="form-control" id="money" placeholder="金额">
                  <span class="help-block"></span>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-10">
                 <textarea class="form-control" rows="3" placeholder="描述信息......"></textarea>
                 <span class="help-block"></span>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-10">
                  <button type="button" class="btn btn-primary btn-block">添加记录</button>
                  <span></span>
                </div>
              </div>
            </form>
          </li>
          <li class="list-group-item">
            <div class="row">
                <div class="col-sm-1">
                  <a class="btn btn-primary">加一顿</a>
                </div>
                <div class="col-sm-1">
                  <a class="btn btn-primary">减一顿</a>
                </div>
            </div>
          </li>
    </ul>
</div>