
<div class="panel panel-default">
    <div class="panel-body">
		<table class="table">
		     <caption><strong>用户增加总金额</strong></caption>
             <thead>
               <tr>
                 <th>用户名</th>
                 <th>总金额</th>
               </tr>
             </thead>
           <tbody>
             <?php foreach ($user_result as $result):?>
              <tr>
                <td><?php echo $result->username?></td>
                <td><?php echo $result->total?> 元</td>
              </tr>
             <?php endforeach;?>
              <tr>
                <th>总金额</th>
                <th><span class="money"><?php echo $total?></span> 元（人民币）</th>
              </tr>
           </tbody>
        </table>
        <table class="table">
            <caption><strong>用户消费总金额</strong></caption>
            <thead>
              <tr>
                <th>用户名</th>
                <th>总金额</th>
              </tr>
            </thead>
            <tbody>
            <?php foreach ($pay_result as $pay):?>
            <tr>
               <td>
                 <div class="col-md-3">
                    <?php echo $pay['username'];?>                   
                 </div>
                 <div class="col-md-1">
                    <span class="badge"><?php echo $pay['user_count'];?></span>
                 </div>
                 <div class="col-md-4"  style="height:20px;">
                   <div class="progress">
                       <div class="progress-bar" role="progressbar" aria-valuenow="<?php echo $pay['user_progress'];?>" 
                                    aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $pay['user_progress'];?>%; min-width: 40px;">
                         <?php echo $pay['user_progress'];?>%
                       </div>
                    </div>
                 </div>
               </td>                
               <td><?php echo $pay['user_pay'];?> 元</td>
            </tr>
            <?php endforeach;?>
            </tbody>
        </table>
        <table class="table">
            <caption><strong>总账单（增加 - 消费）</strong></caption>
          <thead>
              <tr>
                <th>用户名</th>
                <th>应所得金额</th>
              </tr>
          </thead>
          <tbody>
            <?php foreach ($final_result as $final):?>
              <tr>
               <td><?php echo $final['username'];?></td>
               <td><?php echo $final['result_total'];?> 元</td>
              </tr>
            <?php endforeach;?>
          </tbody>
        </table>
	</div>
</div>