<div class="col-md-2">
  <div class="list-group">
    <a href="home/user/get_all_records" class="list-group-item <?php echo $active === 1 ? 'active':''?>">当月消费<span class="badge"><?php echo $count ? $count : 0;?></span></a>
    <a href="home/user/result" class="list-group-item <?php echo $active === 2 ? 'active':''?>">当月统计</a>
    <a href="home/user/info/<?php echo $username;?>" class="list-group-item <?php echo $active === 3 ? 'active':''?>">
      <?php echo $username;?>
    </a>
    <a href="home/user/logout" class="list-group-item">注销登录</a>
  </div>
</div>
<div class="col-md-10">
  <?php echo $panel;?>
</div>