
<div class="row">
	<div class="col-md-12 col-lg-12">
		<form class="form-signin" role="form" action="#">
			<h3 class="form-signin-heading">
				<strong>用户登录</strong>
			</h3>
			<div class="form-group">
				<input type="text" class="form-control" placeholder="用户名">
			</div>
			<div class="form-group">
				<input type="password" class="form-control" placeholder="密码">
			</div>
			<button class="btn btn-lg btn-primary btn-block" type="button">登录</button>
		</form>
	</div>
</div>
<script src="js/login.js"></script>
