<div class="container">
    <div class="row">
        <div class="col-md-12">
          <form class="form-signin" role="form">
            <h3 class="form-signin-heading"><strong>用户注册</strong></h3>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="用户名">
            </div>
            <div class="form-group">
                <input id="password1" type="password" class="form-control" placeholder="密码">
            </div>
            <div class="form-group">
                <input id="password2" type="password" class="form-control" placeholder="重复密码">
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="button">现在注册</button>
           </form>
        </div>
    </div>
</div>
<script src="js/registration.js"></script>